Nm          Jester~
WhoNm       Jes~
AtrPrm      2
Wpn         3701
Guild       3151
Sklladpt    95
Thac0       18
Thac47      9
Hpmin       5
Hpmax       9
Mana        1
Skll         13   1  95 'acid tomato'
Skll          7   1  95 'armor'
Skll         10   1  95 'change sex'
Skll          3   1  95 'chill touch'
Skll          3   1  95 'continual light'
Skll         12   1  95 'control weather'
Skll         14   1  95 'cream pie'
Skll          5   1  95 'create food'
Skll         10   1  95 'create spring'
Skll          5   1  95 'create water'
Skll         12   1  95 'curse'
Skll         24   1  95 'destroy cursed'
Skll          4   1  95 'detect evil'
Skll          7   1  95 'detect invis'
Skll          3   1  95 'detect magic'
Skll          5   1  95 'detect poison'
Skll          4   1  95 'faerie fire'
Skll         14   1  95 'faerie fog'
Skll         15   1  95 'fly'
Skll         11   1  95 'hypnotize'
Skll         16   1  95 'identify'
Skll         10   1  95 'infravision'
Skll          8   1  95 'invis'
Skll          5   1  95 'know alignment'
Skll         13   1  95 'life drain'
Skll         12   1  95 'magic leaf'
Skll         13   1  95 'poison'
Skll         30   1  95 'polymorph other'
Skll          8   1  95 'potato'
Skll         20   1  95 'remove alignment'
Skll         14   1  95 'remove curse'
Skll         15   1  95 'sing courage'
Skll         16   1  95 'sing hope'
Skll         15   1  95 'sing lullaby'
Skll         25   1  95 'sing opera'
Skll         17   1  95 'sing war'
Skll          1   1  95 'ventriloquate'
Skll          7   1  95 'weaken'
Skll          6   1  95 'dodge'
Skll         37   1  95 'fast healing'
Skll         40   1  95 'meditate'
Skll          6   1  95 'scrolls'
Skll         37   1  95 'shield block'
Skll          8   1  95 'singing'
Skll          4   1  95 'sneak'
Skll          9   1  95 'staves'
Skll         15   1  95 'swim'
Skll         11   1  95 'tickles'
Ttle         0 Man~ Woman~
Ttle         1 Moron~ Moron~
Ttle         2 Brainless~ Brainless~
Ttle         3 Braindead~ Braindead~
Ttle         4 Idiot~ Idiot~
Ttle         5 Lesser Fool~ Lesser Fool~
Ttle         6 Fool~ Fool~
Ttle         7 Cry-baby~ Cry-baby~
Ttle         8 Bad Joker~ Bad Joker~
Ttle         9 Practical Joker~ Practical Joker~
Ttle        10 Joker~ Joker~
Ttle        11 Jokester~ Jokesteress~
Ttle        12 Tell Tale~ Tell Tale~
Ttle        13 Story Teller~ Story Teller~
Ttle        14 Bad Singer~ Bad Singer~
Ttle        15 Singer~ Singer~
Ttle        16 Good Singer~ Good Singer~
Ttle        17 Actor~ Actress~
Ttle        18 Lousy Jester~ Lousy Jester~
Ttle        19 Bad Jester~ Bad Jester~
Ttle        20 Jester~ Jester~
Ttle        21 Good Jester~ Good Jester~
Ttle        22 Lesser Master Joker~ Lesser Mistress Joker~
Ttle        23 Master Jokester~ Mistress Jokester~
Ttle        24 Master Jester~ Mistress Jester~
Ttle        25 Master Entertainer~ Mistress Entertainer~
Ttle        26 Master Joker~ Mistress Joker~
Ttle        27 Master Joker~ Mistress Joker~
Ttle        28 Grand Master Joker~ Grand Mistress Joker~
Ttle        29 Grand Master Jokester~ Grand Mistress Jokester~
Ttle        30 Grand Master Jester~ Grand Mistress Jester~
Ttle        31 Grand Master Jester~ Grand Mistress Jester~
Ttle        32 Grand Master Entertainer~ Grand Mistress Entertainer~
Ttle        33 Grand Master Entertainer~ Grand Mistress Entertainer~
Ttle        34 Grand Master Entertainer~ Grand Mistress Entertainer~
Ttle        35 Grand Master Entertainer~ Grand Mistress Entertainer~
Ttle        36 Grand Master Entertainer~ Grand Mistress Entertainer~
Ttle        37 Grand Master Entertainer~ Grand Mistress Entertainer~
Ttle        38 Grand Master Entertainer~ Grand Mistress Entertainer~
Ttle        39 Grand Master Entertainer~ Grand Mistress Entertainer~
Ttle        40 Grand Master Entertainer~ Grand Mistress Entertainer~
Ttle        41 Grand Master Entertainer~ Grand Mistress Entertainer~
Ttle        42 Grand Master Entertainer~ Grand Mistress Entertainer~
Ttle        43 Grand Master Entertainer~ Grand Mistress Entertainer~
Ttle        44 Grand Master Entertainer~ Grand Mistress Entertainer~
Ttle        45 Grand Master Entertainer~ Grand Mistress Entertainer~
Ttle        46 Grand Master Entertainer~ Grand Mistress Entertainer~
Ttle        47 Grand Master Entertainer~ Grand Mistress Entertainer~
Ttle        48 Grand Master Entertainer~ Grand Mistress Entertainer~
Ttle        49 Grand Master Entertainer~ Grand Mistress Entertainer~
Ttle        50 Grand Master Entertainer~ Grand Mistress Entertainer~
Ttle        51 Grand Master Entertainer~ Grand Mistress Entertainer~
Ttle        52 Grand Master Entertainer~ Grand Mistress Entertainer~
Ttle        53 Grand Master Entertainer~ Grand Mistress Entertainer~
Ttle        54 Grand Master Entertainer~ Grand Mistress Entertainer~
Ttle        55 Grand Master Entertainer~ Grand Mistress Entertainer~
Ttle        56 Grand Master Entertainer~ Grand Mistress Entertainer~
Ttle        57 Grand Master Entertainer~ Grand Mistress Entertainer~
Ttle        58 Grand Master Entertainer~ Grand Mistress Entertainer~
Ttle        59 Grand Master Entertainer~ Grand Mistress Entertainer~
Ttle        60 Jester Hero~ Jester Heroine~
Ttle        61 Jester Angel~ Jester Angel~
Ttle        62 Deity of Jesters~ Deity of Jesters~
Ttle        63 Supreme Jester~ Supreme Jester~
Ttle        64 Implementor~ Implementress~
Pose         0 0 You amaze everyone with your singing skills.~
Pose         0 1 $n starts singing a beautiful song.~
Pose         1 0 Your superb punchlines surprise everyone.~
Pose         1 1 $n's superb punchlines surprise everyone in the room.~
Pose         2 0 You wiggle your ears alternately.~
Pose         2 1 $n wiggles $s ears alternately.~
Pose         3 0 Your jokes make everyone roll on the floor laughing.~
Pose         3 1 You roll on the floor laughing from $n's joke.~
Pose         4 0 You nimbly tie yourself into a knot.~
Pose         4 1 $n nimbly ties $mself into a knot.~
Pose         5 0 You juggle with daggers, apples, and eyeballs.~
Pose         5 1 $n juggles with daggers, apples, and eyeballs.~
Pose         6 0 Billy Cristal pats you on your head.~
Pose         6 1 Billy Cristal pats $n's on $s head.~
Pose         7 0 Oof...maybe you shouldn't juggle any more hippopotamuses.~
Pose         7 1 Oof!  Guess $n won't be juggling any more hippos for a while.~
Pose         8 0 You produce a coin from everyone's ear.~
Pose         8 1 $n produces a coin from your ear.~
Pose         9 0 ~
Pose         9 1 ~
Pose        10 0 ~
Pose        10 1 ~
Pose        11 0 ~
Pose        11 1 ~
Pose        12 0 Everyone's pocket explodes with your fireworks.~
Pose        12 1 Your pocket explodes with $n's fireworks.~
Pose        13 0 Jerry Lewis is amused by your jokes.~
Pose        13 1 Jerry Lewis is amused by $n's jokes.~
Pose        14 0 ~
Pose        14 1 ~
Pose        15 0 ~
Pose        15 1 ~
Pose        16 0 ~
Pose        16 1 ~
End
